# Generated by Django 2.0.13 on 2019-04-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.CharField(default='recently', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='due_on',
            field=models.CharField(default='soon', max_length=200),
        ),
    ]
